version: '3.4'

services:
  enterprice.solution.services.webapi:
    image: ${DOCKER_REGISTRY-}enterpricesolutionserviceswebapi
    build:
      context: .
      dockerfile: Enterprice.Solution.Services.WebApi/Dockerfile
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:16